mojaloop/ml-api-adapter

package.json
=> updated common streaming lib for latest version of node-rdkafka

package.json, src/lib/kafka/producer.js, test/unit/lib/kafka/producer.test.js
Hotfix for https://github.com/mojaloop/project/issues/370
=> Hotfix for Issue #370

package.json, src/lib/kafka/producer.js, test/unit/lib/kafka/producer.test.js
Updated Producer factory disconnect function to correctly function against singleton factory pattern. Also fixed Unit tests.
=> PI2 & PI3 Fix for Producer.disconnect()

src/handlers/notification/callbacks.js, test/unit/handlers/notification/callbacks.test.js
Hotfix for https://github.com/mojaloop/ml-api-adapter/issues/31
=> Uncommented out headers on the callback for FSPs

src/handlers/notification/callbacks.js, test/unit/handlers/notification/callbacks.test.js
Fix for https://github.com/mojaloop/ml-api-adapter/issues/34
=> Fix for bug #34

src/handlers/notification/callbacks.js, test/unit/handlers/notification/callbacks.test.js
Fix for https://github.com/mojaloop/ml-api-adapter/issues/34
=> Snapshot release 3.4.0 - Fix for bug #34

config/default.json, package.json, src/handlers/notification/callbacks.js, src/handlers/notification/index.js, test/unit/handlers/notification/callbacks.test.js, test/unit/handlers/notification/index.test.js
Fix for https://github.com/mojaloop/ml-api-adapter/issues/33
=> Snapshot release 3.4.1 - Fix for bug #33

config/default.json, package.json, src/handlers/notification/callbacks.js, src/handlers/notification/index.js, test/unit/handlers/notification/callbacks.test.js, test/unit/handlers/notification/index.test.js
Fix for https://github.com/mojaloop/ml-api-adapter/issues/33
=> Fix for bug #33

src/domain/transfer/index.js, test/unit/domain/transfer/index.test.js
[Story #310](https://github.com/mojaloop/project/issues/310)
=> Feature/310 Handle Payee Rejections

test/functional/api/transfers/post-transfer.test.js
Functional tests fix for the Date Header bug.
=> HTTP Date Header Functional Tests Fix

package.json, src/domain/transfer/transformer.js, src/handlers/notification/callbacks.js, test/unit/domain/transfer/transformer.test.js, test/unit/handlers/notification/callbacks.test.js
https://github.com/mojaloop/project/issues/451
=> Hotfix for #451

test/integration/handlers/notification/index.test.js
fix for integration test failing
=> fix for broken integration tests

package.json
- for central-services-shared and central-services-database;
- Incrementing snapshot version
=> Updating versions 

.gitignore, package-lock.json, package.json, src/shared/plugins.js
version update of logging library
=> updated logger version to new logging framework

config/default.json, package-lock.json, package.json, src/domain/transfer/index.js, src/handlers/notification/index.js, src/lib/utility.js, test/integration-config.json, test/unit/domain/transfer/index.test.js, test/unit/lib/utility.test.js
1. changed the config for prepare topic
2. added the transferId as the kafka message key
```
=============================== Coverage summary ===============================
Statements   : 100% ( 549/549 )
Branches     : 100% ( 109/109 )
Functions    : 100% ( 59/59 )
Lines        : 100% ( 549/549 )
================================================================================
1..156
```
=> Story #575 - combine prepare topics

src/domain/transfer/index.js, src/lib/utility.js
1. separated 'key' and 'opaqueKey'
```
=============================== Coverage summary ===============================
Statements   : 100% ( 549/549 )
Branches     : 100% ( 110/110 )
Functions    : 100% ( 59/59 )
Lines        : 100% ( 549/549 )
================================================================================
1..156
```
=> fixed the kafka message key for story #576

src/api/transfers/handler.js, test/unit/api/transfers/handler.test.js
Changed 200 to 202 for GET /transfers
=> bugfix/Get Transfers To Return 202 Response Code

config/default.json, test/integration-config.json
1. kafka config changes 
```
=============================== Coverage summary ===============================
Statements   : 100% ( 549/549 )
Branches     : 100% ( 110/110 )
Functions    : 100% ( 59/59 )
Lines        : 100% ( 549/549 )
================================================================================
1..156
```
=> Story #577 kafka config changes for performance

README.md, config/default.json, package-lock.json, package.json
added config to create default labels for ml-api on prometheus
=> added config to create default labels for ml-api on prometheus

src/domain/transfer/transformer.js, test/unit/domain/transfer/transformer.test.js
=> feature/737FSPIOP-Signature Header

package-lock.json, package.json, test/integration/handlers/notification/index.test.js, test/unit/api/transfers/routes.test.js
=> feature/742 String Type Error Codes

package-lock.json, package.json, src/domain/transfer/transformer.js, test/unit/domain/transfer/transformer.test.js
Modified SWITCH headers:
- delete: FSPIOP-URI
- to upper case: FSPIOP-HTTP-Method
=> feature/737 FSPIOP-HTTP-Method to ALL-CAPS

docker/central-ledger/default.json
- Updated central-ledger config under docker folder to support v7.4.1 release of central-ledger
=> Hotfix for feature/#941PI7Onboardingenhancementsandfixes

Onboarding.md, docker/central-ledger/default.json, package-lock.json, package.json, src/lib/validator.js
- Updated debug logger in validator to print ISO Timestamp so that the log entry can be useful. Previously milliseconds was not included in the printout which made it tough to debug fine precision comparison when working in the millisecond range.
- Updated onboarding documentation by moving postman script information to the postman repo.
=> Minor update to debug log for validator and updates to onboarding

package.json
=> Bump version to 8.1.0

src/api/transfers/handler.js
=> bugfix/1002 Get Transfer After RecordFundsIn

audit-resolve.json, package-lock.json, package.json
- Apply headers fix from central-services-shared v8.3.1
=> Bugfix: #883 Ensure FSPIOP headers are sent from Switch

audit-resolve.json, docker-compose.yml, docker/central-ledger/default.json, package-lock.json
Updated configs in relation to change in cental-ledger: https://github.com/mojaloop/central-ledger/commit/ff496f9863c4c8857d8a30459ccd9dfa3cfb497b#diff-1e9c3d615e9ebaaaa3669b4c2fd87d00
=> Updated configs for central-ledger docker

Dockerfile, docker-compose.yml, package-lock.json, package.json
Part of #846
- Enable docker to handle both file and console based logging
- update dependencies
=> Feature/846 async logging 

.ncurc.json, package-lock.json, package.json, src/api/metadata/handler.js, src/api/metadata/routes.js, test/helpers.js, test/unit/api/metadata/handler.test.js
- Enable switching between simple and detailed health checks
- Updated dependencies
=> Add simple health check

package-lock.json, src/api/index.js, src/api/transfers/handler.js, src/handlers/index.js, src/handlers/notification/index.js, test/unit/handlers/notification/index.test.js
increased thread pool for node
=> added enhanced logging for performance metrics

.circleci/config.yml, package-lock.json, package.json
- uploads the anchore reports to s3
=> Add anchore summary report upload

package-lock.json, package.json, src/lib/headers.js
fspiop-uri header was missing for PUT operation
=> Changes for bug 1408

.circleci/config.yml
I branched `pisp/master` off of v10.3.1 since v10.3.2 was giving build troubles that I want to push back until after my other work is done.
=> Edited CI to build PISP docker image.

audit-resolve.json, package-lock.json
Ignored low and medium vulns:
- `yargs-parser`
- `sanitize-html`
=> fix(security): fix npm vulnerabilities

Dockerfile
added SSL Support for KAFKA and Event Hub connections
=> feat: added ssl Support

CHANGELOG.md, package-lock.json, package.json, src/api/fxTransfers/routes.js, src/api/transfers/handler.js, src/api/transfers/routes.js, src/api/validationSchemas/commonSchemas.js, src/api/validationSchemas/index.js, src/domain/transfer/dto.js, src/domain/transfer/index.js, src/lib/validator.js, src/shared/constants.js, src/shared/logger/Logger.js, src/shared/logger/index.js, test/unit/api/transfers/handler.test.js, test/unit/api/validationSchemas.test.js, test/unit/domain/transfer/dto.test.js, test/unit/domain/transfer/index.test.js, test/unit/mocks.js, test/unit/shared/constants.test.js, test/unit/shared/logger.test.js
feat(mojaloop/#3574): added fxTransfers endpoints
=> feat(mojaloop/#3574): added fxTransfers endpoints

package-lock.json, package.json, src/domain/participant/index.js, src/handlers/notification/index.js, src/shared/constants.js, test/unit/domain/participant/index.test.js, test/unit/domain/participant/indexSpan.test.js
feat(3574): modified Participant.getEndpoint
=> feat(3574): modified Participant.getEndpoint
